create table if not exists categories
(
    id bigint generated by default as identity
    constraint categories_pkey
    primary key,
    isincome boolean not null,
    name varchar(255)
    );

alter table categories owner to postgres;

create table if not exists users
(
    id bigint generated by default as identity
    constraint users_pkey
    primary key,
    email varchar(255) not null
    constraint uk_6dotkott2kjsp8vw4d0m25fb7
    unique,
    name varchar(255) not null,
    tel varchar(255)
    constraint uk_nekwtc70sk6c2dofve0axwnhb
    unique
    );

alter table users owner to postgres;

create table if not exists accounts
(
    id bigint generated by default as identity
    constraint accounts_pkey
    primary key,
    value double precision not null,
    user_id bigint
    constraint fknjuop33mo69pd79ctplkck40n
    references users
);

alter table accounts owner to postgres;

create table if not exists operations
(
    id bigint generated by default as identity
    constraint operations_pkey
    primary key,
    commited timestamp,
    value double precision not null,
    operation_id bigint
    constraint fkslqff46ww1ue53h1wojht1qvt
    references accounts,
    account_id bigint
    constraint fk3lft1gkkuyvhih1cst48xvm7q
    references accounts
);

alter table operations owner to postgres;

create table if not exists categories_operations
(
    category_id bigint not null
    constraint fk7622hw2d8j97r39wtvmd6vyku
    references categories,
    operation_id bigint not null
    constraint fkcyst1x6r15eon7du3k5vwmb04
    references operations
);

alter table categories_operations owner to postgres;


insert into users (email, name, tel) values ('email@mail.com','Adam','819412');
insert into users (email, name, tel) values ('mail@gmail.com','Sam','09763');
insert into users (email, name, tel) values ('dan@mail.net','Dan','124214');


insert into accounts (value, user_id) values (124,2);
insert into accounts (value, user_id) values (987,2);
insert into accounts (value, user_id) values (98698,2);
insert into accounts (value, user_id) values (888,3);
insert into accounts (value, user_id) values (1851.78,1);
insert into accounts (value, user_id) values (-678,1);


insert into categories (isincome, name) values (true,'salary');
insert into categories (isincome, name) values (false,'tax');
insert into categories (isincome, name) values (false,'food');
insert into categories (isincome, name) values (true,'gift');
insert into categories (isincome, name) values (true,'accident');
insert into categories (isincome, name) values (false,'shopping');

